"""udpate file table

Revision ID: 0ae32b5959d0
Revises: 513cd7b1cef7
Create Date: 2026-02-25 21:27:22.627284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae32b5959d0'
down_revision: Union[str, Sequence[str], None] = '513cd7b1cef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', type_='foreignkey')
    op.create_foreign_key(None, 'details_appro_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('details_cp_file_id_fkey'), 'details_cp', type_='foreignkey')
    op.create_foreign_key(None, 'details_cp', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('recap_rz_file_id_fkey'), 'recap_rz', type_='foreignkey')
    op.create_foreign_key(None, 'recap_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('solde_agents_file_id_fkey'), 'solde_agents', type_='foreignkey')
    op.create_foreign_key(None, 'solde_agents', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_grossiste_livreur', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_grossiste_vers_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_livreur', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_pdv', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'transaction_pdv', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'transaction_livreur', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'transaction_grossiste_vers_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'transaction_grossiste_livreur', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'solde_agents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('solde_agents_file_id_fkey'), 'solde_agents', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'recap_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('recap_rz_file_id_fkey'), 'recap_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'details_cp', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_cp_file_id_fkey'), 'details_cp', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'details_appro_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
