"""update schema for connexion

Revision ID: 0c4869f33fdb
Revises: adab262381ca
Create Date: 2026-03-13 16:20:30.327772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4869f33fdb'
down_revision: Union[str, Sequence[str], None] = 'adab262381ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    op.execute("CREATE SCHEMA IF NOT EXISTS connexion")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', type_='foreignkey')
    op.create_foreign_key(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('details_cp_file_id_fkey'), 'details_cp', type_='foreignkey')
    op.create_foreign_key(op.f('details_cp_file_id_fkey'), 'details_cp', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('recap_rz_file_id_fkey'), 'recap_rz', type_='foreignkey')
    op.create_foreign_key(op.f('recap_rz_file_id_fkey'), 'recap_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('solde_agents_file_id_fkey'), 'solde_agents', type_='foreignkey')
    op.create_foreign_key(op.f('solde_agents_file_id_fkey'), 'solde_agents', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('solde_agents_file_id_fkey'), 'solde_agents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('solde_agents_file_id_fkey'), 'solde_agents', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('recap_rz_file_id_fkey'), 'recap_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('recap_rz_file_id_fkey'), 'recap_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('details_cp_file_id_fkey'), 'details_cp', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_cp_file_id_fkey'), 'details_cp', 'file', ['file_id'], ['id'])
    op.drop_constraint(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
