"""update sheet column name

Revision ID: 17110bb198b0
Revises: 8f75a90876bb
Create Date: 2026-02-21 21:21:23.349362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17110bb198b0'
down_revision: Union[str, Sequence[str], None] = '8f75a90876bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details_appro_rz', sa.Column('nom', sa.String(), nullable=False))
    op.add_column('details_appro_rz', sa.Column('prenom', sa.String(), nullable=False))
    op.drop_constraint(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', type_='foreignkey')
    op.create_foreign_key(None, 'details_appro_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('details_appro_rz', 'prenom_cp')
    op.drop_column('details_appro_rz', 'nom_cp')
    op.drop_constraint(op.f('details_cp_file_id_fkey'), 'details_cp', type_='foreignkey')
    op.create_foreign_key(None, 'details_cp', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('recap_rz', sa.Column('nom', sa.String(), nullable=False))
    op.add_column('recap_rz', sa.Column('prenom', sa.String(), nullable=False))
    op.drop_constraint(op.f('recap_rz_file_id_fkey'), 'recap_rz', type_='foreignkey')
    op.create_foreign_key(None, 'recap_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('recap_rz', 'prenom_cp')
    op.drop_column('recap_rz', 'nom_cp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recap_rz', sa.Column('nom_cp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recap_rz', sa.Column('prenom_cp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recap_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('recap_rz_file_id_fkey'), 'recap_rz', 'file', ['file_id'], ['id'])
    op.drop_column('recap_rz', 'prenom')
    op.drop_column('recap_rz', 'nom')
    op.drop_constraint(None, 'details_cp', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_cp_file_id_fkey'), 'details_cp', 'file', ['file_id'], ['id'])
    op.add_column('details_appro_rz', sa.Column('nom_cp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('details_appro_rz', sa.Column('prenom_cp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'details_appro_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', 'file', ['file_id'], ['id'])
    op.drop_column('details_appro_rz', 'prenom')
    op.drop_column('details_appro_rz', 'nom')
    # ### end Alembic commands ###
