"""create table

Revision ID: 2e2f2163bef8
Revises: 
Create Date: 2026-02-18 21:02:05.200353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2f2163bef8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('live_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('nom_tdp', sa.String(), nullable=False),
    sa.Column('nd_cp', sa.String(), nullable=False),
    sa.Column('nom_cp', sa.String(), nullable=False),
    sa.Column('prenom_cp', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('appro_ume_tdp', sa.BigInteger(), nullable=False),
    sa.Column('appro_cash_td', sa.BigInteger(), nullable=False),
    sa.Column('appro_ume_rz', sa.BigInteger(), nullable=False),
    sa.Column('appro_cash_rz', sa.BigInteger(), nullable=False),
    sa.Column('montant_ci', sa.BigInteger(), nullable=False),
    sa.Column('montant_co', sa.BigInteger(), nullable=False),
    sa.Column('montant_ci_shop', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_service', schema='public')
    op.drop_table('file', schema='public')
    # ### end Alembic commands ###
