"""create table sheet suivi

Revision ID: 513cd7b1cef7
Revises: 17110bb198b0
Create Date: 2026-02-25 21:25:03.791310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513cd7b1cef7'
down_revision: Union[str, Sequence[str], None] = '17110bb198b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solde_agents',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type_agent', sa.String(), nullable=False),
    sa.Column('rattachement', sa.String(), nullable=False),
    sa.Column('agent_msisdn', sa.String(), nullable=False),
    sa.Column('agent_nom', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('transaction_grossiste_livreur',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('msisdn_grossiste', sa.String(), nullable=False),
    sa.Column('msisdn_livreur', sa.String(), nullable=False),
    sa.Column('nombre_transferts_reçus', sa.Integer(), nullable=False),
    sa.Column('montant_transferts_reçus', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('transaction_grossiste_vers_rz',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('msisdn_grossiste', sa.String(), nullable=False),
    sa.Column('msisdn_rz', sa.String(), nullable=False),
    sa.Column('nombre_transferts_reçus', sa.Integer(), nullable=False),
    sa.Column('montant_transferts_reçus', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('transaction_livreur',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('msisdn_livreur', sa.String(), nullable=False),
    sa.Column('msisdn_pdv', sa.String(), nullable=False),
    sa.Column('nombre_transferts_reçus', sa.Integer(), nullable=False),
    sa.Column('montant_transferts_reçus', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('transaction_pdv',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('msisdn_pdv', sa.String(), nullable=False),
    sa.Column('date_activation', sa.Date(), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=False),
    sa.Column('msisdn_rattachement', sa.String(), nullable=False),
    sa.Column('nombre_transactions', sa.Integer(), nullable=False),
    sa.Column('montant_transactions', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('transaction_rz',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('msisdn_rz', sa.String(), nullable=False),
    sa.Column('msisdn_livreur', sa.String(), nullable=False),
    sa.Column('tld_msisdn_rattachement', sa.String(), nullable=False),
    sa.Column('nombre_transferts_reçus', sa.Integer(), nullable=False),
    sa.Column('montant_transferts_reçus', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_constraint(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', type_='foreignkey')
    op.create_foreign_key(None, 'details_appro_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('details_cp_file_id_fkey'), 'details_cp', type_='foreignkey')
    op.create_foreign_key(None, 'details_cp', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('recap_rz_file_id_fkey'), 'recap_rz', type_='foreignkey')
    op.create_foreign_key(None, 'recap_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recap_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('recap_rz_file_id_fkey'), 'recap_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'details_cp', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_cp_file_id_fkey'), 'details_cp', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'details_appro_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', 'file', ['file_id'], ['id'])
    op.drop_table('transaction_rz', schema='public')
    op.drop_table('transaction_pdv', schema='public')
    op.drop_table('transaction_livreur', schema='public')
    op.drop_table('transaction_grossiste_vers_rz', schema='public')
    op.drop_table('transaction_grossiste_livreur', schema='public')
    op.drop_table('solde_agents', schema='public')
    # ### end Alembic commands ###
