"""create table

Revision ID: 78f042280be4
Revises: 2e2f2163bef8
Create Date: 2026-02-21 20:36:27.763408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78f042280be4'
down_revision: Union[str, Sequence[str], None] = '2e2f2163bef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details_appro_rz',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('nom_tdp', sa.String(), nullable=False),
    sa.Column('nd_rz', sa.String(), nullable=False),
    sa.Column('nd_cp', sa.String(), nullable=False),
    sa.Column('nom_cp', sa.String(), nullable=False),
    sa.Column('prenom_cp', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('appro_ume_rz', sa.BigInteger(), nullable=False),
    sa.Column('appro_cash_rz', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('details_cp',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('nom_tdp', sa.String(), nullable=False),
    sa.Column('nd_cp', sa.String(), nullable=False),
    sa.Column('nom_cp', sa.String(), nullable=False),
    sa.Column('prenom_cp', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('appro_ume_tdp', sa.BigInteger(), nullable=False),
    sa.Column('appro_cash_td', sa.BigInteger(), nullable=False),
    sa.Column('appro_ume_rz', sa.BigInteger(), nullable=False),
    sa.Column('appro_cash_rz', sa.BigInteger(), nullable=False),
    sa.Column('montant_ci', sa.BigInteger(), nullable=False),
    sa.Column('montant_co', sa.BigInteger(), nullable=False),
    sa.Column('montant_ci_shop', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('recap_rz',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('nom_tdp', sa.String(), nullable=False),
    sa.Column('nd_tdp', sa.String(), nullable=False),
    sa.Column('nd_rz', sa.String(), nullable=False),
    sa.Column('nom_cp', sa.String(), nullable=False),
    sa.Column('prenom_cp', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('nd_cp_appro', sa.String(), nullable=False),
    sa.Column('appro_cash', sa.BigInteger(), nullable=False),
    sa.Column('appro_ume', sa.BigInteger(), nullable=False),
    sa.Column('montant_ci', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['public.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_table('live_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('nom_tdp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nd_cp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nom_cp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prenom_cp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ville', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('appro_ume_tdp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('appro_cash_td', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('appro_ume_rz', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('appro_cash_rz', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('montant_ci', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('montant_co', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('montant_ci_shop', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('live_service_file_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('live_service_pkey'))
    )
    op.drop_table('recap_rz', schema='public')
    op.drop_table('details_cp', schema='public')
    op.drop_table('details_appro_rz', schema='public')
    # ### end Alembic commands ###
