"""create schema for connexion

Revision ID: adab262381ca
Revises: 557c444a958c
Create Date: 2026-03-13 16:16:19.790927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adab262381ca'
down_revision: Union[str, Sequence[str], None] = '557c444a958c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', type_='foreignkey')
    op.create_foreign_key(None, 'details_appro_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('details_cp_file_id_fkey'), 'details_cp', type_='foreignkey')
    op.create_foreign_key(None, 'details_cp', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('recap_rz_file_id_fkey'), 'recap_rz', type_='foreignkey')
    op.create_foreign_key(None, 'recap_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('solde_agents', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('solde_agents', 'type_agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('solde_agents', 'rattachement',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('solde_agents', 'agent_msisdn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('solde_agents', 'agent_nom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('solde_agents', 'balance',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('solde_agents_file_id_fkey'), 'solde_agents', type_='foreignkey')
    op.create_foreign_key(None, 'solde_agents', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('transaction_grossiste_livreur', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction_grossiste_livreur', 'msisdn_grossiste',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_grossiste_livreur', 'msisdn_livreur',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_grossiste_livreur', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_grossiste_livreur', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_grossiste_livreur', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('transaction_grossiste_vers_rz', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction_grossiste_vers_rz', 'msisdn_grossiste',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_grossiste_vers_rz', 'msisdn_rz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_grossiste_vers_rz', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_grossiste_vers_rz', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_grossiste_vers_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('transaction_livreur', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction_livreur', 'msisdn_livreur',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_livreur', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_livreur', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_livreur', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('transaction_pdv', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction_pdv', 'msisdn_pdv',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_pdv', 'msisdn_rattachement',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_pdv', 'nombre_transactions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_pdv', 'montant_transactions',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_pdv', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('transaction_rz', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transaction_rz', 'msisdn_rz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_rz', 'msisdn_livreur',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_rz', 'tld_msisdn_rattachement',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction_rz', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_rz', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_rz', 'file', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_rz_file_id_fkey'), 'transaction_rz', 'file', ['file_id'], ['id'])
    op.alter_column('transaction_rz', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('transaction_rz', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction_rz', 'tld_msisdn_rattachement',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_rz', 'msisdn_livreur',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_rz', 'msisdn_rz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_rz', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'transaction_pdv', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_pdv_file_id_fkey'), 'transaction_pdv', 'file', ['file_id'], ['id'])
    op.alter_column('transaction_pdv', 'montant_transactions',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('transaction_pdv', 'nombre_transactions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction_pdv', 'msisdn_rattachement',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_pdv', 'msisdn_pdv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_pdv', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'transaction_livreur', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_livreur_file_id_fkey'), 'transaction_livreur', 'file', ['file_id'], ['id'])
    op.alter_column('transaction_livreur', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('transaction_livreur', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction_livreur', 'msisdn_livreur',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_livreur', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'transaction_grossiste_vers_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_vers_rz_file_id_fkey'), 'transaction_grossiste_vers_rz', 'file', ['file_id'], ['id'])
    op.alter_column('transaction_grossiste_vers_rz', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('transaction_grossiste_vers_rz', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction_grossiste_vers_rz', 'msisdn_rz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_grossiste_vers_rz', 'msisdn_grossiste',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_grossiste_vers_rz', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'transaction_grossiste_livreur', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_grossiste_livreur_file_id_fkey'), 'transaction_grossiste_livreur', 'file', ['file_id'], ['id'])
    op.alter_column('transaction_grossiste_livreur', 'montant_transferts_reçus',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('transaction_grossiste_livreur', 'nombre_transferts_reçus',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transaction_grossiste_livreur', 'msisdn_livreur',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_grossiste_livreur', 'msisdn_grossiste',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transaction_grossiste_livreur', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'solde_agents', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('solde_agents_file_id_fkey'), 'solde_agents', 'file', ['file_id'], ['id'])
    op.alter_column('solde_agents', 'balance',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('solde_agents', 'agent_nom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('solde_agents', 'agent_msisdn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('solde_agents', 'rattachement',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('solde_agents', 'type_agent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('solde_agents', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'recap_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('recap_rz_file_id_fkey'), 'recap_rz', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'details_cp', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_cp_file_id_fkey'), 'details_cp', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'details_appro_rz', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('details_appro_rz_file_id_fkey'), 'details_appro_rz', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
